### ISSUE TITLE
CropAreaState's cropRect x/y is always 20 pixels off

### ISSUE THREAD

**Issue by tarngerine** [ailon/cropro#10]
x and y of cropRect start at 20, 20, even though they're rendered at 0, 0. They can even exceed the dimensions of the image!

# Steps to repro
See: https://codesandbox.io/s/gallant-rain-1ilj8z?file=/src/App.tsx

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1629901/184249590-72e155c6-4048-4190-9a67-e86c92ac043b.png">

1. Click image to start cropping
2. Hit check immediately to save/render, with no changes to the crop rect
3. Observe the `getState()` output below: x and y are 20!

<img width="439" alt="image" src="https://user-images.githubusercontent.com/1629901/184249804-0b5329cd-6522-4c15-99c0-57fcdacb4fc3.png">

1. Click image to start cropping
2. Move the top left corner all the way to the bottom right as far as you can
3. Observe the `getState()` output below: x and y exceed the width/height of the image by 10

**Comment by tarngerine** [comment]
it does not break the functionality of the cropper, but it makes it hard to get the cropRect out to preserve it. Our feature preserves the original image and saves the cropped image, too. If a user wants to re-crop it we wish to preserve the previous crop. The crop rect is also used in other situations outside of cropro.

**Comment by ailon** [comment]
Well, I understand that it doesn't look good to the human eyes but it's an internal state that is not supposed to be analyzed or used for something else. The reason for that 20 is that internally it takes the margin into consideration and it's a position of the crop rectangle relative to the UI area and not the image being cropped.

Yes, it could be changed to start at zero and that wouldn't be hard to do, but it would be a breaking change that more users will get hurt by rather than appreciate. So, I'll reserve it for a major version update.

For now, you can just deduct that 20, if you need to use the values for something else.
